import { BitColumn, BitVaryingColumn, BoxColumn, ByteaColumn, CidrColumn, CircleColumn, InetColumn, LineColumn, LsegColumn, MacAddr8Column, MacAddrColumn, PathColumn, PointColumn, PolygonColumn, TsQueryColumn, TsVectorColumn, UUIDColumn, XMLColumn } from './column-types/string';
import { IntervalColumn, TimeColumn } from './column-types/date-time';
import { BooleanColumn } from './column-types/boolean';
import { TimestampHelpers } from './timestamps';
import { CustomTypeColumn, DomainColumn } from './column-types/custom-type';
import { SqlFn } from '../query/expressions/raw-sql';
import { TableData } from '../tableData';
import { PostgisGeographyPointColumn } from './column-types/postgis';
import { ColumnSchemaConfig } from './column-schema';
import { Column } from './column';
export declare const getColumnTypes: <ColumnTypes, Shape extends Column.QueryColumnsInit>(types: ColumnTypes, fn: (t: ColumnTypes) => Shape, nowSQL: string | undefined, language: string | undefined) => Shape;
export interface DefaultColumnTypes<SchemaConfig extends ColumnSchemaConfig> extends TimestampHelpers {
    schema: SchemaConfig;
    enum: SchemaConfig['enum'];
    array: SchemaConfig['array'];
    name<T>(this: T, name: string): T;
    sql: SqlFn;
    smallint: SchemaConfig['smallint'];
    integer: SchemaConfig['integer'];
    bigint: SchemaConfig['bigint'];
    numeric: SchemaConfig['decimal'];
    decimal: SchemaConfig['decimal'];
    real: SchemaConfig['real'];
    doublePrecision: SchemaConfig['doublePrecision'];
    identity(options?: TableData.Identity): Column.HasDefault<ReturnType<SchemaConfig['integer']>>;
    smallSerial: SchemaConfig['smallSerial'];
    serial: SchemaConfig['serial'];
    bigSerial: SchemaConfig['bigSerial'];
    money: SchemaConfig['money'];
    varchar: SchemaConfig['varchar'];
    text: SchemaConfig['text'];
    string: SchemaConfig['string'];
    citext: SchemaConfig['citext'];
    bytea(): ByteaColumn<SchemaConfig>;
    date: SchemaConfig['date'];
    timestampNoTZ: SchemaConfig['timestampNoTZ'];
    timestamp: SchemaConfig['timestamp'];
    time(precision?: number): TimeColumn<SchemaConfig>;
    interval(fields?: string, precision?: number): IntervalColumn<SchemaConfig>;
    boolean(): BooleanColumn<SchemaConfig>;
    point(): PointColumn<SchemaConfig>;
    line(): LineColumn<SchemaConfig>;
    lseg(): LsegColumn<SchemaConfig>;
    box(): BoxColumn<SchemaConfig>;
    path(): PathColumn<SchemaConfig>;
    polygon(): PolygonColumn<SchemaConfig>;
    circle(): CircleColumn<SchemaConfig>;
    cidr(): CidrColumn<SchemaConfig>;
    inet(): InetColumn<SchemaConfig>;
    macaddr(): MacAddrColumn<SchemaConfig>;
    macaddr8(): MacAddr8Column<SchemaConfig>;
    bit(length: number): BitColumn<SchemaConfig>;
    bitVarying(length?: number): BitVaryingColumn<SchemaConfig>;
    tsvector(): TsVectorColumn<SchemaConfig>;
    tsquery(): TsQueryColumn<SchemaConfig>;
    uuid(): UUIDColumn<SchemaConfig>;
    xml(): XMLColumn<SchemaConfig>;
    json: SchemaConfig['json'];
    jsonText: SchemaConfig['jsonText'];
    type(dataType: string): CustomTypeColumn<SchemaConfig>;
    domain(dataType: string): DomainColumn<SchemaConfig>;
    geography: {
        point(): PostgisGeographyPointColumn<SchemaConfig>;
    };
}
export declare const makeColumnTypes: <SchemaConfig extends ColumnSchemaConfig>(schema: SchemaConfig) => DefaultColumnTypes<SchemaConfig>;
